export enum Text {
    menuOptionStartPage = 'Главная страница',
    menuOptionLoginPage = 'Авторизация',
    menuOptionWordList = 'Список слов',
    menuOptionMiniGames = 'Мини-игры',
    menuOptionStatPage = 'Статистика',
    headerAppName = 'RS•',
    headerAppNameSpan = 'Lang',
    headerAppNameMotto = 'изучай английский играючи',
    loginButtonValue = 'Войти',
    footerRsSchool = 'Javascript/Front-end 2021Q3',
    footerGithubLinksItem1 = 'SergeyKozlovskiy',
    footerGithubLinksItem2 = 'VoitihovichP',
    footerGithubLinksItem3 = 'Stellarator85',
}

export enum Classes {
    headerContainer = 'Header-container',
    menuContainer = 'Menu-container',
    menuButton = 'Menu-button',
    menuList = 'Menu-list',
    menuListItem = 'Menu-list_item',
    menuListItemOption = 'Menu-list_item__option',
    headerAppName = 'Header_app-name',
    headerAppNameSpan = 'Header_app-name__span',
    headerAppNameMotto = 'Header_app-name__motto',
    loginButton = 'Log-in-button',
    footer = 'Footer',
    footerRsSchool = 'Footer_RS-school',
    footerGithubLinks = 'Footer_Github-links',
    footerGithubLinksItem = 'Footer_Github-links__item',
}